name: 'Deployment overview'
description: 'Create an overview MD file in the root of the repository'
author: darko.krizic@prodyna.com
inputs:
  organization:
      description: 'The organization to monitor'
      required: true
  repositories:
    description: 'The list of repositories to monitor'
    required: true
  environments:
    description: 'The list of environments to monitor'
    required: true
    default: 'dev,staging,prod'
  environment-links:
    description: 'The list of links to the environments'
    required: true
    default: 'https://dev.example.com,https://staging.example.com,https://prod.example.com'
  verbose:
    description: 'The verbosity level'
    required: true
    default: 1
  github-token:
    description: 'The token to use for the GitHub API'
    required: true
  title:
    description: 'The title of the overview'
    required: true
    default: 'Deployment overview'
  target-json-file:
    description: 'The file to write the JSON to'
    required: false
    default: 'deployment-overview.json'
  target-md-file:
    description: 'The file to write the MD to'
    required: false
    default: 'deployment-overview.md'
  template-file:
    description: 'The template file to use'
    required: false
    default: '/template/default.tpl'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/prodyna/deployment-overview:v0.4'
  env:
    ORGANIZATION: ${{ inputs.organization }}
    REPOSITORIES: ${{ inputs.repositories }}
    ENVIRONMENTS: ${{ inputs.environments }}
    ENVIRONMENT_LINKS: ${{ inputs.environment-links }}
    VERBOSE: ${{ inputs.verbose }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    TITLE: ${{ inputs.title }}
    TEMPLATE_FILE: ${{ inputs.template-file }}
    TARGET_JSON_FILE: ${{ inputs.target-json-file }}
    TARGET_MD_FILE: ${{ inputs.target-md-file }}
