name: 'Deployment overview'
description: 'Create an overview MD file in the root of the repository'
author: darko.krizic@prodyna.com
inputs:
  organization:
      description: 'The organization to monitor'
      required: true
  repositories:
    description: 'The list of repositories to monitor'
    required: true
  environments:
    description: 'The list of environments to monitor'
    required: true
    default: 'dev,staging,prod'
  environment-links:
    description: 'The list of links to the environments'
    required: true
    default: 'https://dev.example.com,https://staging.example.com,https://prod.example.com'
  verbose:
    description: 'The verbosity level'
    required: true
    default: 1
  target-repository:
    description: 'The repository where the overview will be written to'
    required: true
    default: '.github'
  target-repository-file:
    description: 'The file where the overview will be written to'
    required: true
    default: 'profile/README.md'
  github-token:
    description: 'The token to use for the GitHub API'
    required: true
  title:
    description: 'The title of the overview'
    required: true
    default: 'Deployment overview'
  template-file:
    description: 'The template file to use for the overview'
    required: true
    default: '/gihub/workflow/template/default.tpl'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --organization=${{ inputs.organization }}
    - --repositories=${{ inputs.repositories }}
    - --environments=${{ inputs.environments }}
    - --environment-links=${{ inputs.environment-links }}
    - --verbose=${{ inputs.verbose }}
    - --target-repository=${{ inputs.target-repository }}
    - --target-repository-file=${{ inputs.target-repository-file }}
    - --github-token=${{ inputs.github-token }}
    - --title=${{ inputs.title }}
    - --template-file=${{ inputs.template-file }}
